version: '3.3'

services:
  postgres:
    container_name: postgres
    user: "root"
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORTS=${POSTGRES_PORTS}
    ports:
      - ${POSTGRES_PORTS}
    restart: on-failure
