version: '3.3'

services:
  postgres:
    container_name: postgres
    env_file: docker-compose/.env
    user: "root"
    image: postgres
    ports:
      - ${POSTGRES_PORTS}
    volumes:
      - pg:/var/lib/postgresql/data
    restart: on-failure
volumes:
  pg:
    name: "pg"

