version: '3.3'

services:
  postgres:
    container_name: postgres
    env_file: docker-compose/.env
    user: "root"
    image: postgres
    ports:
      - ${POSTGRES_PORTS}
    restart: on-failure

