version: '3.3'

services:
  postgres:
    image: postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.05'
          memory: 256M
    ports:
      - 5432:5432/tcp
    restart: always
    command: postgres -c 'max_connections=200'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: expenses-it
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
