version: '3.3'

services:
  postgres:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    restart: always

    environment:
      POSTGRES_DB: expenses
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
