version: '3.3'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432/tcp
    restart: always

    environment:
      POSTGRES_DB: expenses
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
