version: '3.3'

services:
  postgres:
    image: postgres
    ports:
      - "127.0.0.1:5433:5433"
    restart: always

    environment:
      POSTGRES_DB: expenses-it
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
